name: PHP Quality Assurance
on: [push, pull_request]
jobs:

    Unit_Tests:
        runs-on: ubuntu-latest
        if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}

        strategy:
            matrix:
                php: ['7.2', '7.3', '7.4']
                prefer:
                    - "lowest"
                    - "highest"
                ignore-platform:
                    - ""
                experimental:
                    - false
                include:
                    - php: "8.0"
                      prefer: "highest"
                      ignore-platform: "--ignore-platform-reqs"
                      experimental: true

        continue-on-error: ${{ matrix.experimental }}

        steps:
            - uses: actions/checkout@v2

            - name: Setup PHP version
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}

            - name: Check syntax error in sources
              run: find ./src/ ./tests/src/ ./tests/cases/ -type f -name '*.php' -print0 | xargs -0 -L 1 -P 4 -- php -l

            - name: Install dependencies
              uses: "ramsey/composer-install@v1"
              with:
                  dependency-versions: ${{ matrix.prefer }}
                  composer-options: ${{ matrix.ignore-platform }}

            - name: Run integration tests
              run: ./vendor/bin/phpunit --testsuite=integration --no-coverage

            - name: Run unit tests
              run: ./vendor/bin/phpunit --testsuite=unit --no-coverage

    Static_Analisys:
        runs-on: ubuntu-latest
        if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}

        steps:
            - uses: actions/checkout@v2

            - name: Setup PHP version
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '7.4'

            - name: Install dependencies
              uses: "ramsey/composer-install@v1"

            - name: Check code styles
              run: ./vendor/bin/phpcs

            - name: Check cross-version PHP compatibility
              run: composer phpcompat

            - name: Check Psalm
              run: ./vendor/bin/psalm --show-info=false --no-progress --output-format=compact
